name: s17 Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    
    - name: Run validation tests
      run: |
        pytest test_validate.py -v
    
    - name: Run merging tests
      run: |
        pytest test_merge.py -v
    
    - name: Check test results
      run: |
        if [ $? -eq 0 ]; then
          echo "All tests passed successfully!"
        else
          echo "Some tests failed!"
          exit 1
        fi 